version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: booking_place_postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d mydatabase"]
      interval: 5s
      timeout: 5s
      retries: 5

  bookingplace:
    build:
      context: .
      args:
        - VERSION=1.0.0
    container_name: booking_place_app
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/mydatabase
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: mypassword
      SPRING_JPA_HIBERNATE_DDL-AUTO: validate

  frontend:
    image: nginx:alpine
    container_name: my_frontend
    volumes:
      - ./frontend-dist/build:/usr/share/nginx/html
    ports:
      - "3000:80"

volumes:
  postgres_data: